name: em_widgets
description: "English Mind reusable widgets."

publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  em_theme: 0.0.1
  em_vocabulary: 0.0.1

  flutter_svg: 2.0.17
  heroicons_flutter: 0.4.0
  flutter_hooks: 0.21.2
  collection: 1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  em_lints: 0.0.1
  build_runner: 2.4.14
  index_generator: 4.0.1
  flutter_gen_runner: 5.9.0

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
  assets:
    exclude:
      - ../em_vocabulary/assets/svg/**

flutter:
  uses-material-design: true

  assets:
    - assets/flags/
    - assets/cat_emojis/
    - assets/cat_stickers/
    - ../em_vocabulary/assets/svg/
