import 'package:em_theme/em_theme.dart';
import 'package:em_widgets/constants/constants.dart';
import 'package:em_widgets/gen/assets.gen.dart';
import 'package:flutter/widgets.dart';

enum FlagIconSize { s, m, l }

class EmFlagIcon extends StatelessWidget {
  final FlagIcon icon;
  final FlagIconSize size;
  final AlignmentGeometry alignment;
  final ColorFilter? colorFilter;

  const EmFlagIcon(
    this.icon, {
    this.size = FlagIconSize.m,
    this.alignment = Alignment.center,
    this.colorFilter,
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    final size = switch (this.size) {
      FlagIconSize.s => context.textScaler.scale(16.0),
      FlagIconSize.m => context.textScaler.scale(24.0),
      FlagIconSize.l => context.textScaler.scale(32.0),
    };

    return icon.asset.svg(
      width: size,
      height: size,
      alignment: alignment,
      package: packageName,
      colorFilter: colorFilter,
      semanticsLabel: 'flag ${icon.name}',
    );
  }
}

enum FlagIcon {
  abkhazia,
  afghanistan,
  alandIslands,
  albania,
  algeria,
  americanSamoa,
  andorra,
  angola,
  anguilla,
  antiguaAndBarbuda,
  argentina,
  armenia,
  aruba,
  australia,
  austria,
  azerbaijan,
  azoresIslands,
  bahamas,
  bahrain,
  balearicIslands,

  bangladesh,
  barbados,
  basqueCountry,
  belarus,
  belgium,
  belize,
  benin,
  bermuda,
  bhutan,
  bolivia,
  bonaire,
  bosniaAndHerzegovina,
  botswana,
  brazil,
  britishColumbia,
  britishIndianOceanTerritory,
  britishVirginIslands,
  brunei,
  bulgaria,
  burkinaFaso,
  burundi,
  cambodia,
  cameroon,
  canada,
  canaryIslands,
  capeVerde,
  caymanIslands,
  centralAfricanRepublic,
  ceuta,
  chad,
  chile,
  china,
  christmasIsland,
  cocosIslands,
  colombia,
  comoros,
  cookIslands,
  corsica,
  costaRica,
  croatia,
  cuba,
  curacao,
  cyprus,
  czechRepublic,
  democraticRepublicOfTheCongo,
  denmark,
  djibouti,
  dominica,
  dominicanRepublic,
  eastTimor,
  ecuador,
  egypt,
  elSalvador,
  england,
  equatorialGuinea,
  eritrea,
  estonia,
  ethiopia,
  europeanUnion,
  falklandIslands,
  faeroeIslands,
  fiji,
  finland,
  france,
  frenchPolynesia,
  gabon,
  galapagosIslands,
  gambia,
  georgia,
  germany,
  ghana,
  gibraltar,
  greece,
  greenland,
  grenada,
  guam,
  guatemala,
  guernsey,
  guineaBissau,
  guinea,
  guyana,
  haiti,
  hawaii,
  honduras,
  hongKong,
  hungary,
  iceland,
  india,
  indonesia,
  iran,
  iraq,
  ireland,
  isleOfMan,
  israel,
  italy,
  ivoryCoast,
  jamaica,
  japan,
  jersey,
  jordan,
  kazakhstan,
  kenya,
  kiribati,
  kosovo,
  kuwait,
  kyrgyzstan,
  laos,
  latvia,
  lebanon,
  lesotho,
  liberia,
  libya,
  liechtenstein,
  lithuania,
  luxembourg,
  macao,
  madagascar,
  madeira,
  malawi,
  malaysia,
  maldives,
  mali,
  malta,
  marshallIslands,
  martinique,
  mauritius,
  mexico,
  micronesia,
  moldova,
  monaco,
  mongolia,
  montenegro,
  montserrat,
  morocco,
  mozambique,
  myanmar,
  namibia,
  nauru,
  nepal,
  netherlands,
  newZealand,
  nicaragua,
  niger,
  nigeria,
  niue,
  norfolkIsland,
  northKorea,
  northCyprus,
  northernMarianaIslands,
  norway,
  oman,
  orkneyIslands,
  ossetia,
  pakistan,
  palau,
  palestine,
  panama,
  papuaNewGuinea,
  paraguay,
  peru,
  philippines,
  pitcairnIslands,
  poland,
  portugal,
  puertoRico,
  qatar,
  rapaNui,
  republicOfMacedonia,
  republicOfTheCongo,
  romania,
  russia,
  rwanda,
  sabaIsland,
  sahrawiArabDemocraticRepublic,
  saintKittsAndNevis,
  samoa,
  sanMarino,
  saoTomeAndPrincipe,
  sardinia,
  saudiArabia,
  scotland,
  senegal,
  serbia,
  seychelles,
  sierraLeone,
  singapore,
  sintEustatius,
  sintMaarten,
  slovakia,
  slovenia,
  solomonIslands,
  somalia,
  somaliland,
  southAfrica,
  southKorea,
  southSudan,
  spain,
  sriLanka,
  stBarts,
  stLucia,
  stVincentAndTheGrenadines,
  sudan,
  suriname,
  swaziland,
  sweden,
  switzerland,
  syria,
  taiwan,
  tajikistan,
  tanzania,
  thailand,
  tibet,
  togo,
  tonga,
  transnistria,
  trinidadAndTobago,
  tunisia,
  turkey,
  turkmenistan,
  turksAndCaicosIslands,
  tuvalu,
  uganda,
  ukraine,
  unitedArabEmirates,
  unitedKingdom,
  unitedNations,
  unitedStates,
  uruguay,
  uzbekistan,
  vanuatu,
  vaticanCity,
  venezuela,
  vietnam,
  virginIslands,
  wales,
  yemen,
  zambia,
  zimbabwe;

  SvgGenImage get asset {
    return switch (this) {
      FlagIcon.wales => Assets.flags.wales,
      FlagIcon.virginIslands => Assets.flags.virginIslands,
      FlagIcon.vaticanCity => Assets.flags.vaticanCity,
      FlagIcon.unitedNations => Assets.flags.unitedNations,
      FlagIcon.unitedStates => Assets.flags.unitedStates,
      FlagIcon.tonga => Assets.flags.tonga,
      FlagIcon.transnistria => Assets.flags.transnistria,
      FlagIcon.turkmenistan => Assets.flags.turkmenistan,
      FlagIcon.tibet => Assets.flags.tibet,
      FlagIcon.togo => Assets.flags.togo,
      FlagIcon.swaziland => Assets.flags.swaziland,
      FlagIcon.stBarts => Assets.flags.stBarts,
      FlagIcon.stLucia => Assets.flags.stLucia,
      FlagIcon.stVincentAndTheGrenadines =>
        Assets.flags.stVincentAndTheGrenadines,
      FlagIcon.somaliland => Assets.flags.somaliland,
      FlagIcon.sintEustatius => Assets.flags.sintEustatius,
      FlagIcon.sintMaarten => Assets.flags.sintMaarten,
      FlagIcon.serbia => Assets.flags.serbia,
      FlagIcon.senegal => Assets.flags.senegal,
      FlagIcon.scotland => Assets.flags.scotland,
      FlagIcon.seychelles => Assets.flags.seychelles,
      FlagIcon.sierraLeone => Assets.flags.sierraLeone,
      FlagIcon.sardinia => Assets.flags.sardinia,
      FlagIcon.sabaIsland => Assets.flags.sabaIsland,
      FlagIcon.sahrawiArabDemocraticRepublic =>
        Assets.flags.sahrawiArabDemocraticRepublic,
      FlagIcon.saintKittsAndNevis => Assets.flags.saintKittsAndNevis,
      FlagIcon.rapaNui => Assets.flags.rapaNui,
      FlagIcon.republicOfMacedonia => Assets.flags.republicOfMacedonia,
      FlagIcon.republicOfTheCongo => Assets.flags.republicOfTheCongo,
      FlagIcon.romania => Assets.flags.romania,
      FlagIcon.russia => Assets.flags.russia,
      FlagIcon.rwanda => Assets.flags.rwanda,
      FlagIcon.norfolkIsland => Assets.flags.norfolkIsland,
      FlagIcon.northKorea => Assets.flags.northKorea,
      FlagIcon.northCyprus => Assets.flags.northernCyprus,
      FlagIcon.northernMarianaIslands => Assets.flags.northernMarianasIslands,
      FlagIcon.niue => Assets.flags.niue,
      FlagIcon.madeira => Assets.flags.madeira,
      FlagIcon.madagascar => Assets.flags.madagascar,
      FlagIcon.malawi => Assets.flags.malawi,
      FlagIcon.malaysia => Assets.flags.malaysia,
      FlagIcon.maldives => Assets.flags.maldives,
      FlagIcon.mali => Assets.flags.mali,
      FlagIcon.martinique => Assets.flags.martinique,
      FlagIcon.mauritius => Assets.flags.mauritius,
      FlagIcon.mexico => Assets.flags.mexico,
      FlagIcon.micronesia => Assets.flags.micronesia,
      FlagIcon.moldova => Assets.flags.moldova,
      FlagIcon.monaco => Assets.flags.monaco,
      FlagIcon.mongolia => Assets.flags.mongolia,
      FlagIcon.montenegro => Assets.flags.montenegro,
      FlagIcon.montserrat => Assets.flags.montserrat,
      FlagIcon.morocco => Assets.flags.morocco,
      FlagIcon.mozambique => Assets.flags.mozambique,
      FlagIcon.myanmar => Assets.flags.myanmar,
      FlagIcon.namibia => Assets.flags.namibia,
      FlagIcon.nauru => Assets.flags.nauru,
      FlagIcon.eastTimor => Assets.flags.eastTimor,
      FlagIcon.england => Assets.flags.england,
      FlagIcon.equatorialGuinea => Assets.flags.equatorialGuinea,
      FlagIcon.eritrea => Assets.flags.eritrea,
      FlagIcon.estonia => Assets.flags.estonia,
      FlagIcon.ethiopia => Assets.flags.ethiopia,
      FlagIcon.europeanUnion => Assets.flags.europeanUnion,
      FlagIcon.falklandIslands => Assets.flags.falklandIslands,
      FlagIcon.faeroeIslands => Assets.flags.faroeIslands,
      FlagIcon.fiji => Assets.flags.fiji,
      FlagIcon.finland => Assets.flags.finland,
      FlagIcon.france => Assets.flags.france,
      FlagIcon.frenchPolynesia => Assets.flags.frenchPolynesia,
      FlagIcon.gabon => Assets.flags.gabon,
      FlagIcon.galapagosIslands => Assets.flags.galapagosIslands,
      FlagIcon.gambia => Assets.flags.gambia,
      FlagIcon.georgia => Assets.flags.georgia,
      FlagIcon.germany => Assets.flags.germany,
      FlagIcon.ghana => Assets.flags.ghana,
      FlagIcon.gibraltar => Assets.flags.gibraltar,
      FlagIcon.greece => Assets.flags.greece,
      FlagIcon.greenland => Assets.flags.greenland,
      FlagIcon.grenada => Assets.flags.grenada,
      FlagIcon.guernsey => Assets.flags.guernsey,
      FlagIcon.guineaBissau => Assets.flags.guineaBissau,
      FlagIcon.guinea => Assets.flags.guinea,
      FlagIcon.guyana => Assets.flags.guyana,
      FlagIcon.haiti => Assets.flags.haiti,
      FlagIcon.hawaii => Assets.flags.hawaii,
      FlagIcon.honduras => Assets.flags.honduras,
      FlagIcon.hongKong => Assets.flags.hongKong,
      FlagIcon.hungary => Assets.flags.hungary,
      FlagIcon.iceland => Assets.flags.iceland,
      FlagIcon.india => Assets.flags.india,
      FlagIcon.indonesia => Assets.flags.indonesia,
      FlagIcon.iran => Assets.flags.iran,
      FlagIcon.iraq => Assets.flags.iraq,
      FlagIcon.ireland => Assets.flags.ireland,
      FlagIcon.isleOfMan => Assets.flags.isleOfMan,
      FlagIcon.israel => Assets.flags.israel,
      FlagIcon.italy => Assets.flags.italy,
      FlagIcon.ivoryCoast => Assets.flags.ivoryCoast,
      FlagIcon.jamaica => Assets.flags.jamaica,
      FlagIcon.japan => Assets.flags.japan,
      FlagIcon.jersey => Assets.flags.jersey,
      FlagIcon.jordan => Assets.flags.jordan,
      FlagIcon.kazakhstan => Assets.flags.kazakhstan,
      FlagIcon.kenya => Assets.flags.kenya,
      FlagIcon.kiribati => Assets.flags.kiribati,
      FlagIcon.kosovo => Assets.flags.kosovo,
      FlagIcon.kuwait => Assets.flags.kuwait,
      FlagIcon.kyrgyzstan => Assets.flags.kyrgyzstan,
      FlagIcon.laos => Assets.flags.laos,
      FlagIcon.latvia => Assets.flags.latvia,
      FlagIcon.lebanon => Assets.flags.lebanon,
      FlagIcon.lesotho => Assets.flags.lesotho,
      FlagIcon.abkhazia => Assets.flags.abkhazia,
      FlagIcon.afghanistan => Assets.flags.afghanistan,
      FlagIcon.alandIslands => Assets.flags.alandIslands,
      FlagIcon.albania => Assets.flags.albania,
      FlagIcon.algeria => Assets.flags.algeria,
      FlagIcon.americanSamoa => Assets.flags.americanSamoa,
      FlagIcon.andorra => Assets.flags.andorra,
      FlagIcon.angola => Assets.flags.angola,
      FlagIcon.anguilla => Assets.flags.anguilla,
      FlagIcon.antiguaAndBarbuda => Assets.flags.antiguaAndBarbuda,
      FlagIcon.argentina => Assets.flags.argentina,
      FlagIcon.armenia => Assets.flags.armenia,
      FlagIcon.aruba => Assets.flags.aruba,
      FlagIcon.australia => Assets.flags.australia,
      FlagIcon.austria => Assets.flags.austria,
      FlagIcon.azerbaijan => Assets.flags.azerbaijan,
      FlagIcon.azoresIslands => Assets.flags.azoresIslands,
      FlagIcon.bahamas => Assets.flags.bahamas,
      FlagIcon.bahrain => Assets.flags.bahrain,
      FlagIcon.balearicIslands => Assets.flags.balearicIslands,
      FlagIcon.bangladesh => Assets.flags.bangladesh,
      FlagIcon.barbados => Assets.flags.barbados,
      FlagIcon.basqueCountry => Assets.flags.basqueCountry,
      FlagIcon.belarus => Assets.flags.belarus,
      FlagIcon.belgium => Assets.flags.belgium,
      FlagIcon.belize => Assets.flags.belize,
      FlagIcon.benin => Assets.flags.benin,
      FlagIcon.bermuda => Assets.flags.bermuda,
      FlagIcon.bhutan => Assets.flags.bhutan,
      FlagIcon.bolivia => Assets.flags.bolivia,
      FlagIcon.bonaire => Assets.flags.bonaire,
      FlagIcon.bosniaAndHerzegovina => Assets.flags.bosniaAndHerzegovina,
      FlagIcon.botswana => Assets.flags.botswana,
      FlagIcon.brazil => Assets.flags.brazil,
      FlagIcon.britishColumbia => Assets.flags.britishColumbia,
      FlagIcon.britishIndianOceanTerritory =>
        Assets.flags.britishIndianOceanTerritory,
      FlagIcon.britishVirginIslands => Assets.flags.britishVirginIslands,
      FlagIcon.brunei => Assets.flags.brunei,
      FlagIcon.bulgaria => Assets.flags.bulgaria,
      FlagIcon.burkinaFaso => Assets.flags.burkinaFaso,
      FlagIcon.burundi => Assets.flags.burundi,
      FlagIcon.canaryIslands => Assets.flags.canaryIslands,
      FlagIcon.cambodia => Assets.flags.cambodia,
      FlagIcon.cameroon => Assets.flags.cameroon,
      FlagIcon.canada => Assets.flags.canada,
      FlagIcon.capeVerde => Assets.flags.capeVerde,
      FlagIcon.caymanIslands => Assets.flags.caymanIslands,
      FlagIcon.centralAfricanRepublic => Assets.flags.centralAfricanRepublic,
      FlagIcon.ceuta => Assets.flags.ceuta,
      FlagIcon.chad => Assets.flags.chad,
      FlagIcon.chile => Assets.flags.chile,
      FlagIcon.china => Assets.flags.china,
      FlagIcon.christmasIsland => Assets.flags.christmasIsland,
      FlagIcon.cocosIslands => Assets.flags.cocosIsland,
      FlagIcon.colombia => Assets.flags.colombia,
      FlagIcon.cookIslands => Assets.flags.cookIslands,
      FlagIcon.costaRica => Assets.flags.costaRica,
      FlagIcon.comoros => Assets.flags.comoros,
      FlagIcon.corsica => Assets.flags.corsica,
      FlagIcon.croatia => Assets.flags.croatia,
      FlagIcon.cuba => Assets.flags.cuba,
      FlagIcon.curacao => Assets.flags.curacao,
      FlagIcon.cyprus => Assets.flags.cyprus,
      FlagIcon.czechRepublic => Assets.flags.czechRepublic,
      FlagIcon.democraticRepublicOfTheCongo =>
        Assets.flags.democraticRepublicOfCongo,
      FlagIcon.denmark => Assets.flags.denmark,
      FlagIcon.djibouti => Assets.flags.djibouti,
      FlagIcon.dominica => Assets.flags.dominica,
      FlagIcon.dominicanRepublic => Assets.flags.dominicanRepublic,
      FlagIcon.ecuador => Assets.flags.ecuador,
      FlagIcon.egypt => Assets.flags.egypt,
      FlagIcon.elSalvador => Assets.flags.elSalvador,
      FlagIcon.guam => Assets.flags.guam,
      FlagIcon.guatemala => Assets.flags.guatemala,
      FlagIcon.liberia => Assets.flags.liberia,
      FlagIcon.libya => Assets.flags.libya,
      FlagIcon.liechtenstein => Assets.flags.liechtenstein,
      FlagIcon.lithuania => Assets.flags.lithuania,
      FlagIcon.luxembourg => Assets.flags.luxembourg,
      FlagIcon.macao => Assets.flags.macao,
      FlagIcon.malta => Assets.flags.malta,
      FlagIcon.marshallIslands => Assets.flags.marshallIsland,
      FlagIcon.nepal => Assets.flags.nepal,
      FlagIcon.netherlands => Assets.flags.netherlands,
      FlagIcon.newZealand => Assets.flags.newZealand,
      FlagIcon.nicaragua => Assets.flags.nicaragua,
      FlagIcon.niger => Assets.flags.niger,
      FlagIcon.nigeria => Assets.flags.nigeria,
      FlagIcon.norway => Assets.flags.norway,
      FlagIcon.oman => Assets.flags.oman,
      FlagIcon.orkneyIslands => Assets.flags.orkneyIslands,
      FlagIcon.ossetia => Assets.flags.ossetia,
      FlagIcon.pakistan => Assets.flags.pakistan,
      FlagIcon.palau => Assets.flags.palau,
      FlagIcon.palestine => Assets.flags.palestine,
      FlagIcon.panama => Assets.flags.panama,
      FlagIcon.papuaNewGuinea => Assets.flags.papuaNewGuinea,
      FlagIcon.paraguay => Assets.flags.paraguay,
      FlagIcon.peru => Assets.flags.peru,
      FlagIcon.philippines => Assets.flags.philippines,
      FlagIcon.pitcairnIslands => Assets.flags.pitcairnIslands,
      FlagIcon.poland => Assets.flags.poland,
      FlagIcon.portugal => Assets.flags.portugal,
      FlagIcon.puertoRico => Assets.flags.puertoRico,
      FlagIcon.qatar => Assets.flags.qatar,
      FlagIcon.samoa => Assets.flags.samoa,
      FlagIcon.sanMarino => Assets.flags.sanMarino,
      FlagIcon.saoTomeAndPrincipe => Assets.flags.saoTomeAndPrince,
      FlagIcon.saudiArabia => Assets.flags.saudiArabia,
      FlagIcon.singapore => Assets.flags.singapore,
      FlagIcon.slovakia => Assets.flags.slovakia,
      FlagIcon.slovenia => Assets.flags.slovenia,
      FlagIcon.solomonIslands => Assets.flags.solomonIslands,
      FlagIcon.somalia => Assets.flags.somalia,
      FlagIcon.southAfrica => Assets.flags.southAfrica,
      FlagIcon.southKorea => Assets.flags.southKorea,
      FlagIcon.southSudan => Assets.flags.southSudan,
      FlagIcon.spain => Assets.flags.spain,
      FlagIcon.sriLanka => Assets.flags.sriLanka,
      FlagIcon.sudan => Assets.flags.sudan,
      FlagIcon.suriname => Assets.flags.suriname,
      FlagIcon.sweden => Assets.flags.sweden,
      FlagIcon.switzerland => Assets.flags.switzerland,
      FlagIcon.syria => Assets.flags.syria,
      FlagIcon.taiwan => Assets.flags.taiwan,
      FlagIcon.tajikistan => Assets.flags.tajikistan,
      FlagIcon.tanzania => Assets.flags.tanzania,
      FlagIcon.thailand => Assets.flags.thailand,
      FlagIcon.trinidadAndTobago => Assets.flags.trinidadAndTobago,
      FlagIcon.tunisia => Assets.flags.tunisia,
      FlagIcon.turkey => Assets.flags.turkey,
      FlagIcon.turksAndCaicosIslands => Assets.flags.turksAndCaicos,
      FlagIcon.tuvalu => Assets.flags.tuvalu,
      FlagIcon.uganda => Assets.flags.uganda,
      FlagIcon.ukraine => Assets.flags.ukraine,
      FlagIcon.unitedArabEmirates => Assets.flags.unitedArabEmirates,
      FlagIcon.unitedKingdom => Assets.flags.unitedKingdom,
      FlagIcon.uruguay => Assets.flags.uruguay,
      FlagIcon.uzbekistan => Assets.flags.uzbekistan,
      FlagIcon.vanuatu => Assets.flags.vanuatu,
      FlagIcon.venezuela => Assets.flags.venezuela,
      FlagIcon.vietnam => Assets.flags.vietnam,
      FlagIcon.yemen => Assets.flags.yemen,
      FlagIcon.zambia => Assets.flags.zambia,
      FlagIcon.zimbabwe => Assets.flags.zimbabwe,
    };
  }
}
