name: english_mind_demo
description: "English Mind demo showcasing new gamification features."

publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  em_theme: 0.0.1
  em_widgets: 0.0.1
  em_vocabulary: 0.0.1
  get_it: 8.0.3
  audioplayers: 6.2.0
  auto_route: 9.3.0+1
  flutter_hooks: 0.21.2
  logger: 2.5.0
  confetti: 0.8.0
  heroicons_flutter: 0.4.0
  speech_to_text: 7.0.0
  objectbox: 4.1.0
  objectbox_flutter_libs: 4.1.0
  path_provider: 2.1.5
  path: 1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  em_lints: 0.0.1
  build_runner: 2.4.14
  auto_route_generator: 9.0.0
  objectbox_generator: 4.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - ../../packages/em_vocabulary/assets/svg/
    - ../../packages/em_vocabulary/assets/json/

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-ExtraLight.ttf
        - asset: assets/fonts/ReadexPro-Light.ttf
        - asset: assets/fonts/ReadexPro-Regular.ttf
        - asset: assets/fonts/ReadexPro-Medium.ttf
        - asset: assets/fonts/ReadexPro-SemiBold.ttf
        - asset: assets/fonts/ReadexPro-Bold.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
